import type { LiqueAmpTheme } from '../../types/theme';

// Default palette sampled from liqueampui.png: green-black background,
// forest-charcoal surfaces, warm orange/peach accent, muted mint secondary.
export const LIQUEAMP_DEFAULT: LiqueAmpTheme = {
  id: 'liqueamp-default',
  name: 'LiqueAmp Default',
  version: 1,
  source: 'builtin',
  colors: {
    bg: '#0b100e',
    surface: '#101815',
    surface2: '#15201b',
    surface3: '#1b2923',
    border: '#2a3b33',
    borderSubtle: '#1d2a24',
    borderStrong: '#3f5749',
    text: '#efe5d5',
    textSecondary: '#c3b9a7',
    textMuted: '#8a978d',
    textDisabled: '#56635a',
    primary: '#ff7a3d',
    secondary: '#8fcfa9',
    accent: '#ff8a4c',
    accentBright: '#ffb07a',
    success: '#7fd49a',
    warning: '#f2b544',
    danger: '#ff5a4f',
    info: '#72b9d6',
    live: '#ff5a3c',
    visualizer: '#ff7a3d',
    visualizerSecondary: '#d6d86a',
    glow: '#ff7a3d',
    glowStrong: '#ffa066',
    focus: '#ffb07a',
  },
  effects: { glowEnabled: true, glowIntensity: 0.6, borderRadius: 2 },
};

export const AMBER_NIGHT: LiqueAmpTheme = {
  id: 'amber-night',
  name: 'Amber Night',
  version: 1,
  source: 'builtin',
  colors: {
    bg: '#0e0b08',
    surface: '#15110c',
    surface2: '#1c1710',
    surface3: '#241d14',
    border: '#3a2e1f',
    borderSubtle: '#2a2117',
    borderStrong: '#5a4630',
    text: '#f4e3c3',
    textSecondary: '#cdb993',
    textMuted: '#9a8767',
    textDisabled: '#5e5040',
    primary: '#ffb000',
    secondary: '#e0c080',
    accent: '#ffc233',
    accentBright: '#ffd97a',
    success: '#b8d46a',
    warning: '#ffb000',
    danger: '#ff5f3f',
    info: '#d9b36a',
    live: '#ff7a1a',
    visualizer: '#ffb000',
    visualizerSecondary: '#ff7a1a',
    glow: '#ffb000',
    glowStrong: '#ffd060',
    focus: '#ffd97a',
  },
  effects: { glowEnabled: true, glowIntensity: 0.7, borderRadius: 0 },
};

export const BUILTIN_THEMES: readonly LiqueAmpTheme[] = [LIQUEAMP_DEFAULT, AMBER_NIGHT];
